const express = require('express');
const { body, validationResult } = require('express-validator');
const router = express.Router();
const pool = require('../db');
const { rotateLink } = require('../utils/linkRotation');
const { sendEvent: sendMetaEvent, userDataFromReq } = require('../utils/metaCapi');
// assignNewLead is not called from this route in the split deployment — see
// the pg_notify block in the POST handler. The lead-assigner runs only on
// the CRM service (driven by the 'lead.created' notification).

function computeLeadScore(sugarLevel, duration) {
  if (duration === 'pre') return 2;
  const sugarScore = sugarLevel === '250+' ? 3 : 2;
  const durationBonus = { long: 2, mid: 1, new: 0 }[duration] ?? 0;
  return Math.min(5, sugarScore + durationBonus);
}

function getISTDayOfWeek() {
  const now = new Date();
  return now.toLocaleString('en-US', { timeZone: 'Asia/Kolkata', weekday: 'short' });
}

/* Lead-quality value used as Meta `value` so the optimization model
   bids on the qualification profile, not just the conversion event.
   Must stay in sync with funnel-meta/frontend/funnel/src/utils/pixel.js
   SCORE_MAP — otherwise browser pixel + server CAPI ship different
   `rolling_value` numbers for the same lead.

   The `age_group` DB column now stores the Tamil-knowledge answer
   ('yes' / 'no') for the Meta funnel. Only those two values contribute
   to the score. Any historical row whose age_group still holds a legacy
   age bucket ('35-45' etc.) simply contributes zero — by request, age is
   not part of the bidding model anymore. */
function leadQualificationValue({ sugar_level, diabetes_duration, on_medication, age_group, occupation }) {
  const SCORES = {
    sugar:      { '150-250': 80, '250+': 120 },
    duration:   { new: 60, mid: 100, long: 150 },
    medication: { none: 60, tablets: 110, insulin: 160 },
    // Only yes/no on the Tamil question carries any weight. Tamil-yes is
    // higher because the webinar is delivered in Tamil — Tamil-no leads
    // are still tracked but contribute the lower of the two values.
    tamil:      { yes: 120, no: 50 },
    occupation: { working: 130, retired: 110, housewife: 90 },
  };
  let v = 0;
  if (sugar_level && SCORES.sugar[sugar_level])                v += SCORES.sugar[sugar_level];
  if (diabetes_duration && SCORES.duration[diabetes_duration]) v += SCORES.duration[diabetes_duration];
  if (on_medication && SCORES.medication[on_medication])       v += SCORES.medication[on_medication];
  if (age_group && SCORES.tamil[age_group])                     v += SCORES.tamil[age_group];
  if (occupation && SCORES.occupation[occupation])              v += SCORES.occupation[occupation];
  return v;
}

const validators = [
  body('full_name').trim().isLength({ min: 2 }).matches(/^[a-zA-Z\s]+$/),
  body('whatsapp_number').trim().matches(/^\d{10}$/),
  body('email').trim().isEmail().normalizeEmail(),
  body('sugar_level').isIn(['150-250', '250+']),
  body('diabetes_duration').isIn(['new', 'mid', 'long', 'pre']),
  body('language_pref').isIn(['tamil', 'english']),
  // New single-page funnel qualification fields (optional for back-compat
  // with old multi-page funnels still posting the original 6-field shape).
  body('on_medication').optional({ nullable: true }).isIn(['insulin', 'tablets', 'none']),
  // The `age_group` column was repurposed on the Meta funnel to record the
  // answer to "Do you know Tamil?" (yes/no). Old age-bucket values are kept
  // in the allow-list so back-compat with the YT funnel + any in-flight
  // browser sessions on the previous build is preserved.
  body('age_group').optional({ nullable: true }).isIn(['35-45', '45-55', '55+', 'yes', 'no']),
  body('occupation').optional({ nullable: true }).isIn(['working', 'housewife', 'retired']),
  // Meta CAPI dedup — UUID generated by the browser pixel and shared here
  // so server-side + client-side events count as one in Events Manager.
  body('meta_event_id').optional({ nullable: true }).isString().isLength({ max: 64 }),
  body('meta_event_id_cr').optional({ nullable: true }).isString().isLength({ max: 64 }),
  body('fbp').optional({ nullable: true }).isString().isLength({ max: 100 }),
  body('fbc').optional({ nullable: true }).isString().isLength({ max: 200 }),
];

const ALLOWED_SOURCES = new Set(['meta', 'yt']);
function normalizeSource(value) {
  return ALLOWED_SOURCES.has(value) ? value : 'meta';
}

router.post('/leads', validators, async (req, res) => {
  const errors = validationResult(req);
  if (!errors.isEmpty()) {
    return res.status(422).json({
      success: false,
      error: 'validation_failed',
      fields: errors.array().map(e => e.path),
    });
  }

  const source = normalizeSource(req.body.source);

  // Fetch config for this source
  let config = { kill_switch: false, tuesday_whatsapp_link: '', friday_whatsapp_link: '' };
  try {
    const { rows } = await pool.query(
      'SELECT kill_switch, tuesday_whatsapp_link, friday_whatsapp_link FROM webinar_config WHERE source = $1',
      [source]
    );
    if (rows.length > 0) config = rows[0];
  } catch (err) {
    console.warn('Config fetch warning:', err.message);
  }

  if (config.kill_switch) {
    return res.status(409).json({ success: false, error: 'registrations_paused' });
  }

  const { full_name, whatsapp_number, email, sugar_level, diabetes_duration,
          language_pref, on_medication, age_group, occupation,
          utm_source, utm_campaign, utm_content, fbclid } = req.body;

  // Visitor ID from the client's localStorage. Lets us tie this lead to
  // its pre-registration page_visited events for Option-C unique-visitor
  // dedupe via the lead's phone number.
  const visitor_id = typeof req.body.visitor_id === 'string'
    ? req.body.visitor_id.slice(0, 64)
    : null;

  // Meta CAPI dedup fields (browser + server fire same event_id).
  const metaEventId   = typeof req.body.meta_event_id    === 'string' ? req.body.meta_event_id    : null;
  const metaEventIdCr = typeof req.body.meta_event_id_cr === 'string' ? req.body.meta_event_id_cr : null;
  const fbp           = typeof req.body.fbp              === 'string' ? req.body.fbp              : null;
  const fbc           = typeof req.body.fbc              === 'string' ? req.body.fbc              : null;

  const lead_score = computeLeadScore(sugar_level, diabetes_duration);
  const day = getISTDayOfWeek();
  const whatsapp_link = (day === 'Mon' || day === 'Tue')
    ? config.tuesday_whatsapp_link
    : config.friday_whatsapp_link;

  // Look up the currently active webinar session for this source
  let webinar_id = null;
  try {
    const { rows: wRows } = await pool.query(
      'SELECT id FROM webinars WHERE is_active = TRUE AND source = $1 LIMIT 1',
      [source]
    );
    webinar_id = wRows[0]?.id ?? null;
  } catch (_) { /* webinars table may not exist yet — safe to skip */ }

  try {
    const { rows } = await pool.query(
      `INSERT INTO leads
        (full_name, whatsapp_number, email, sugar_level, diabetes_duration,
         language_pref, on_medication, age_group, occupation,
         lead_score, utm_source, utm_campaign, utm_content, fbclid,
         webinar_id, source, visitor_id,
         meta_event_id, meta_event_id_cr, fbp, fbc)
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21)
       RETURNING id`,
      [
        full_name, whatsapp_number, email, sugar_level, diabetes_duration,
        language_pref, on_medication || null, age_group || null, occupation || null,
        lead_score,
        utm_source || null, utm_campaign || null, utm_content || null, fbclid || null,
        webinar_id, source, visitor_id,
        metaEventId, metaEventIdCr, fbp, fbc,
      ]
    );

    res.status(201).json({
      success: true,
      lead_id: rows[0].id,
      lead_score,
      whatsapp_link,
    });

    // Fire-and-forget: rotate WhatsApp link if lead count crossed a threshold
    if (webinar_id) {
      rotateLink(webinar_id).catch(e => console.error('[LinkRotation] post-lead error:', e.message));
    }

    // Fire-and-forget: round-robin assign this lead to an eligible caller.
    //
    // Post-split this no longer happens in-process — funnel-meta and funnel-yt
    // don't run the assigner directly because the round-robin state lives on
    // the CRM service. Instead we fire pg_notify('lead.created') and the CRM
    // service's LISTEN handler picks it up and runs assignNewLead there.
    //
    // The single-process app.js dev entry registers its OWN LISTEN handler
    // for the same channel so this still works end-to-end in dev mode.
    if (webinar_id) {
      pool.query(
        `SELECT pg_notify('lead.created', $1)`,
        [JSON.stringify({
          leadId:     rows[0].id,
          source,
          sugarLevel: sugar_level,
          webinarId:  webinar_id,
        })]
      ).catch(e => console.error('[Assigner notify] post-lead error:', e.message));
    }

    // Fire-and-forget: Meta Conversions API — Lead + CompleteRegistration.
    // Shares meta_event_id with the browser Pixel so Events Manager
    // dedupes the two transports automatically. If META_CAPI_ACCESS_TOKEN
    // is unset, sendMetaEvent silently no-ops (see utils/metaCapi.js).
    if (metaEventId) {
      const [firstName, ...restName] = (full_name || '').trim().split(/\s+/);
      const lastName = restName.join(' ');
      const userData = userDataFromReq(req, {
        email,
        phone: whatsapp_number,
        first_name: firstName,
        last_name: lastName,
      });
      // `value` + `currency` are intentionally NOT included in custom_data —
      // we don't want Meta's bid model driven by a synthetic monetary value.
      // `rolling_value` is sent as a CUSTOM key for our own analytics only.
      const rollingValue = leadQualificationValue({ sugar_level, diabetes_duration, on_medication, age_group, occupation });
      const customData = {
        content_name: 'webinar_registration',
        content_category: 'lead',
        lead_score,
        rolling_value: rollingValue,
        sugar_level,
        diabetes_duration,
        on_medication: on_medication || null,
        // Mirror the browser pixel — the `age_group` DB column now holds
        // the Tamil-knowledge answer (yes/no), so the CAPI custom_data
        // key is renamed `knows_tamil` to match Meta Events Manager.
        knows_tamil: age_group || null,
        occupation: occupation || null,
      };
      const sourceUrl = req.body.event_source_url || req.headers.referer || undefined;
      sendMetaEvent({ event_name: 'Lead', event_id: metaEventId, event_source_url: sourceUrl, user_data: userData, custom_data: customData })
        .catch(e => console.error('[metaCapi] Lead error:', e.message));
      // CompleteRegistration uses a derived event_id so the browser
      // pixel's CompleteRegistration (different UUID) also dedupes.
      const crEventId = metaEventIdCr || (metaEventId + ':cr');
      sendMetaEvent({ event_name: 'CompleteRegistration', event_id: crEventId, event_source_url: sourceUrl, user_data: userData, custom_data: { ...customData, status: true } })
        .catch(e => console.error('[metaCapi] CompleteRegistration error:', e.message));
    }
  } catch (err) {
    console.error('Lead insert error:', err.message);
    res.status(500).json({ success: false, error: 'server_error' });
  }
});

/* PATCH /api/leads/:id/wa-click */
router.patch('/leads/:id/wa-click', async (req, res) => {
  const { id } = req.params;
  if (!id) return res.status(400).json({ success: false });

  try {
    const { rows } = await pool.query(
      `UPDATE leads SET wa_clicked = true WHERE id = $1
       RETURNING full_name, whatsapp_number, email, sugar_level,
                 diabetes_duration, on_medication, age_group, occupation,
                 lead_score`,
      [id]
    );
    res.json({ success: true });

    // Fire-and-forget: Meta CAPI Schedule event — the strongest commitment
    // signal we have. Browser Pixel fires the same event with the matching
    // meta_event_id, so they dedupe in Events Manager.
    const metaEventId = typeof req.body?.meta_event_id === 'string' ? req.body.meta_event_id : null;
    const lead = rows[0];
    if (metaEventId && lead) {
      const [firstName, ...restName] = (lead.full_name || '').trim().split(/\s+/);
      const lastName = restName.join(' ');
      const userData = userDataFromReq(req, {
        email: lead.email,
        phone: lead.whatsapp_number,
        first_name: firstName,
        last_name: lastName,
      });
      const rollingValue = leadQualificationValue(lead);
      const customData = {
        content_name: 'webinar_attendance_committed',
        content_category: 'schedule',
        lead_score: lead.lead_score,
        rolling_value: rollingValue,
      };
      const sourceUrl = req.body?.event_source_url || req.headers.referer || undefined;
      sendMetaEvent({ event_name: 'Schedule', event_id: metaEventId, event_source_url: sourceUrl, user_data: userData, custom_data: customData })
        .catch(e => console.error('[metaCapi] Schedule error:', e.message));
    }
  } catch (err) {
    console.error('wa-click update error:', err.message);
    res.status(500).json({ success: false });
  }
});

module.exports = router;
module.exports._computeLeadScore = computeLeadScore;
module.exports._getISTDayOfWeek  = getISTDayOfWeek;
